version: "{build}"
clone_depth: 1
clone_folder: c:\gopath\src\github.com\rhysd\github-clone-all
environment:
    GOPATH: c:\gopath
    GO111MODULE: on
install:
    - echo %PATH%
    - echo %GOPATH%
    - go version
    - go env
    - go get -v -t -d ./...
build: off
test_script:
    - go build
    - go test -v -race -coverprofile=coverage.txt ./ghca
after_test:
    - choco install codecov
    - codecov -f coverage.txt
deploy: off
