language: go
os:
  - linux
  - osx
env:
  - GO111MODULE=on
install:
  - go get -t -d -v ./...
  - go version
  - go env
script:
  - go build
  - go test -v -race -coverprofile=coverage.txt ./ghca
after_success:
  - bash <(curl -s https://codecov.io/bash)
